import Razorpay from 'razorpay'

export const razorpay = process.env.RAZORPAY_KEY_ID && process.env.RAZORPAY_KEY_SECRET
  ? new Razorpay({
      key_id: process.env.RAZORPAY_KEY_ID,
      key_secret: process.env.RAZORPAY_KEY_SECRET,
    })
  : null

export const RAZORPAY_LAUNCH_PLANS = {
  PRO: {
    name: 'Growth',
    dbPlanKey: 'GROWTH' as const,
    priceMonthly: 1999,
    priceAnnual: 23988,
    currency: 'INR' as const,
    trialDays: 90,
    mode: 'subscription' as const,
    razorpayPlanId: process.env.RAZORPAY_LAUNCH_PRO_PLAN_ID || '',
    features: [
      'Up to 50 interviews/month',
      'All AI levels (L0-L4)',
      'Full audit reports',
      'Priority support',
      'Custom question library',
      'Calendar & scheduling',
      '5 team members',
    ],
    limits: {
      interviewsPerMonth: 50,
      maxAILevel: 4,
      customQuestions: true,
      auditReports: true,
      teamMembers: 5,
      apiAccess: false,
    },
  },
  ENTERPRISE: {
    name: 'Enterprise',
    dbPlanKey: 'ENTERPRISE' as const,
    priceMonthly: 7999,
    priceAnnual: 95988,
    currency: 'INR' as const,
    trialDays: 90,
    mode: 'contact_sales' as const,
    razorpayPlanId: process.env.RAZORPAY_LAUNCH_ENTERPRISE_PLAN_ID || '',
    features: [
      'Unlimited interviews',
      'All AI levels (L0-L4)',
      'Advanced analytics',
      'Dedicated support',
      'SSO & SAML',
      'Custom integrations',
      'On-prem deployment',
    ],
    limits: {
      interviewsPerMonth: Infinity,
      maxAILevel: 4,
      customQuestions: true,
      auditReports: true,
      teamMembers: Infinity,
      apiAccess: true,
    },
  },
  PAY_PER_INTERVIEW: {
    name: 'Pay Per Interview',
    dbPlanKey: 'PAY_PER_INTERVIEW' as const,
    priceMonthly: 999,
    priceAnnual: 0,
    currency: 'INR' as const,
    trialDays: 0,
    mode: 'payment' as const,
    razorpayPlanId: process.env.RAZORPAY_LAUNCH_PPI_PLAN_ID || '',
    features: [
      'Rs.999 per interview session',
      'All AI levels (L0-L4)',
      'AI audit report included',
      'No monthly commitment',
      'Pay only when you interview',
    ],
    limits: {
      interviewsPerMonth: Infinity,
      maxAILevel: 4,
      customQuestions: true,
      auditReports: true,
      teamMembers: 1,
      apiAccess: false,
    },
  },
  CANDIDATE_PRO: {
    name: 'Candidate Pro',
    dbPlanKey: 'CANDIDATE_PRO' as const,
    priceMonthly: 199,
    priceAnnual: 2388,
    currency: 'INR' as const,
    trialDays: 0,
    mode: 'subscription' as const,
    razorpayPlanId: process.env.RAZORPAY_LAUNCH_CANDIDATE_PRO_PLAN_ID || '',
    features: [
      'Full practice platform access',
      '4,000+ problems in 7 languages',
      'AI-powered hints and guidance',
      'Progress tracking & analytics',
      'Daily challenges & streaks',
    ],
    limits: {
      interviewsPerMonth: 0,
      maxAILevel: 4,
      customQuestions: false,
      auditReports: false,
      teamMembers: 1,
      apiAccess: false,
    },
  },
  EDUCATION: {
    name: 'Education',
    dbPlanKey: 'EDUCATION' as const,
    priceMonthly: 249,
    priceAnnual: 2988,
    currency: 'INR' as const,
    trialDays: 90,
    mode: 'subscription' as const,
    razorpayPlanId: process.env.RAZORPAY_LAUNCH_EDUCATION_PLAN_ID || '',
    features: [
      'Per-student pricing (Rs.249/student/month)',
      'Full problem bank access',
      'AI assist (L0-L4)',
      'Student progress tracking',
      'Assignment management',
      'Class analytics',
      'Enrollment codes',
      'CSV export',
    ],
    limits: {
      interviewsPerMonth: 0,
      maxAILevel: 4,
      customQuestions: true,
      auditReports: false,
      teamMembers: 1,
      apiAccess: false,
    },
  },
} as const

export type RazorpayLaunchPlanKey = keyof typeof RAZORPAY_LAUNCH_PLANS
